apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smlite-checkoutservice
  annotations:
     kubernetes.io/ingress.class: "tier-2-cpx"
     ingress.citrix.com/insecure-service-type: "tcp"
     ingress.citrix.com/insecure-port: "5050"
spec:
    backend:
        serviceName: checkoutservice-app
        servicePort: 5050
